using System.Reflection;

// Automatically generated by AssemblyInfo.tt on Saturday, September 23, 2023 08:19:05 PM
[assembly: AssemblyVersion("2023.09.23.2019")]
[assembly: AssemblyFileVersion("2023.09.23.2019")]